////Logo change with greating
function change(){
    document.getElementById('greet').innerHTML='WELCOME TO THE BEST STREAMING';

}
function options(){
    let movies=[
        'Predator','Bugonia','Playdate','TYRON'
    ];
    movies=['Predator','Bugonia','Playdate','TYRON'];
    typeof movies
    'array';
    let $movies=prompt('Select a Movie,Sopie To watch'); alert(movies);
    if(movies==$movies){
        console.log('Playing');
    }else(movies!==$movies);{
console.log(movies[4] +'Options Available');
    }
}

function queries(){
alert('Foward Your Query @MANDYDIMAKATSO12@gmail.com');
}
function dev(){
    document.getElementById('dev').textContent='<MANDY/>';
}
function sesArhch(){
    let movies=[
        'Predator','Bugonia','Playdate','TYRON'
    ];
    movies=['Predator','Bugonia','Playdate','TYRON'];
    typeof movies
    'array';
    document.getElementById('movies-search').innerHTML=movies[3];
    if(movies ==[3]){
        alert('Movie Currently In Play');
    }else (movies !=[2]);{
console.log(movies[3] +' Currently In Play')
    }
}
function select(){
    let lan='ENGLISH';
    lan='ENGLISH';
    typeof lan
    'string';
    let Lan='Portoguese';
    Lan='ENGLISH';
    typeof Lan
    'string';
    console.log(lan + ' Language Selected');
}
